// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwfggqmp-mIA46iF9EFLHVDGpz1-419Uk',
    appId: '1:91967795530:web:168545a6e5c468d4fed1b3',
    messagingSenderId: '91967795530',
    projectId: 'pluto-notifications-b7087',
    authDomain: 'pluto-notifications-b7087.firebaseapp.com',
    storageBucket: 'pluto-notifications-b7087.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYy8MIMbkuXuFFBToBZ9VtqvWVHocyoA',
    appId: '1:91967795530:android:f4116f0dc312770efed1b3',
    messagingSenderId: '91967795530',
    projectId: 'pluto-notifications-b7087',
    storageBucket: 'pluto-notifications-b7087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLu-RdIqHo2O0WIFF5dbfyCx6czwxS4A',
    appId: '1:91967795530:ios:089e7aa091e7d6dbfed1b3',
    messagingSenderId: '91967795530',
    projectId: 'pluto-notifications-b7087',
    storageBucket: 'pluto-notifications-b7087.firebasestorage.app',
    iosBundleId: 'com.example.plutoUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyLu-RdIqHo2O0WIFF5dbfyCx6czwxS4A',
    appId: '1:91967795530:ios:089e7aa091e7d6dbfed1b3',
    messagingSenderId: '91967795530',
    projectId: 'pluto-notifications-b7087',
    storageBucket: 'pluto-notifications-b7087.firebasestorage.app',
    iosBundleId: 'com.example.plutoUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwfggqmp-mIA46iF9EFLHVDGpz1-419Uk',
    appId: '1:91967795530:web:8f8f22f8b035ab7cfed1b3',
    messagingSenderId: '91967795530',
    projectId: 'pluto-notifications-b7087',
    authDomain: 'pluto-notifications-b7087.firebaseapp.com',
    storageBucket: 'pluto-notifications-b7087.firebasestorage.app',
  );
}
